### ISSUE TITLE
Live demo with full code ?

### ISSUE THREAD

**Issue by martingazak** [gberaudo/olwind#9]
Hello,
the live demo https://gberaudo.github.io/olwind/ looks very interesting, but the bundle.js used in it seems to be a compressed / obfuscated Javascript, not a version of OLWIND project present on github.
Is it possible to create the version of demo using the actual version of OLWIND library ?
Thanks.

**Comment by gberaudo** [comment]
Hi @martingazak, the demo is built from the source code available in the repository.
If you want unminified content, you can change the "mode" in the webpack command in the package.json.
